language: c

services:
  - docker

before_install:
  - docker pull igormoreno/usi-pf1:friendlyhello
  # - docker build -t friendlyhello .
  - docker container run -it --rm --mount type=bind,source="$(pwd)",target=/app --workdir=/app friendlyhello bash ./script.sh

script:
  - echo hoi
