services:
  - docker

before_install:
  - docker build -t friendlyhello .
  - docker container run -it --rm --mount type=bind,source="$(pwd)",target=/app --workdir=/app friendlyhello bash ./script.sh

script:
  - bash ./script.sh
